- name: Create AMQ Subscription
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'amq-sub.yaml.j2') }}"
  register: rbac_result
  when: not delete_deployment|bool
  tags: 
    - amq
    - acm-workload

# wait for AMQ to be ready
- name: Wait for AMQ CRD to be ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "{{ project_namespace }}"
    field_selectors:
      - metadata.name={{ amqstartingCSV }}
  register: r_amq_crd
  retries: 20
  delay: 60
  until: r_amq_crd.resources | list | length == 1
  when: not delete_deployment|bool
  tags: 
    - amq
    - acm-workload

- name: Display AMQ install status
  debug:
    var: r_amq_crd.resources[0].status
  when: not delete_deployment|bool
  tags: 
    - amq
    - acm-workload

- name: Setting amq installed fact
  set_fact:
    amq_installed: "{{ r_amq_crd.resources[0].status }}"
  ignore_errors: false
  when: not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: fail when AMQ subscription if not ready
  fail:
    msg: AMQ subscription is not Present on cluster
  when: amq_installed is not defined and not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Create kafka instance
  kubernetes.core.k8s:
    state: present
    namespace:  "{{ project_namespace }}"
    definition: "{{ lookup('template', 'amq-kafka-instance.yaml.j2') }}"
  when: not delete_deployment|bool
  tags: 
    - amq
    - acm-workload

- name: Search for all Pods labeled  cafe-cluster-zookeeper
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - "strimzi.io/name=cafe-cluster-zookeeper"
    field_selectors:
      - status.phase=Running
  register: r_zookeeper_status
  retries: 200
  delay: 10
  until: r_zookeeper_status.resources  | list | length == 3
  when: not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Search for all Pods labeled  cafe-cluster-kafka
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - "strimzi.io/name=cafe-cluster-kafka"
    field_selectors:
      - status.phase=Running
  register: r_kafka_status
  retries: 200
  delay: 10
  until: r_kafka_status.resources  | list | length == 3
  when: not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Create kafka topics
  kubernetes.core.k8s:
    state: present
    namespace:  "{{ project_namespace }}"
    definition: "{{ lookup('template', 'amq-kafka-topics.yaml.j2') }}"
  when: not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Create kafdrop
  kubernetes.core.k8s:
    state: present
    namespace:  "{{ project_namespace }}"
    definition: "{{ lookup('template', 'kafdrop.yaml.j2') }}"
  when: not delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Remove kafdrop
  kubernetes.core.k8s:
    state: absent
    namespace:  "{{ project_namespace }}"
    definition: "{{ lookup('template', 'kafdrop.yaml.j2') }}"
  ignore_errors: yes
  when: delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Remove kafka topics
  command: "{{ oc_location }}  delete -f {{ config_location }}amq-kafka-topics.yaml"
  ignore_errors: yes
  when: delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Remove kafka instance
  kubernetes.core.k8s:
    state: absent
    namespace:  "{{ project_namespace }}"
    definition: "{{ lookup('template', 'amq-kafka-instance.yaml.j2') }}"
  ignore_errors: yes
  when: delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Waiting for  kafka instances to be deleted
  shell: |
    set -o pipefail && {{ oc_location }} get pods  -n {{ project_namespace }} | grep Running | grep {{ kafka_cluster_name }} | wc -l
  register: install_status
  when: delete_deployment|bool
  until: "'No resources found' in install_status.stderr or '0' in install_status.stdout"
  retries: 60
  delay: 15
  ignore_errors: yes
  args:
    executable: /bin/bash
  tags:
    - amq
    - acm-workload

- name: Remove AMQ Subscription
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'amq-sub.yaml.j2') }}"
  ignore_errors: yes
  when: delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Remove AMQ Subscription
  command: "{{ oc_location }}  delete -f {{ config_location }}amqstreams.v1.6.1.yaml"
  ignore_errors: yes
  when: delete_deployment|bool
  tags:
    - amq
    - acm-workload

- name: Remove AMQ
  command: "{{ oc_location }}  delete csv {{ amqstartingCSV }} -n {{ project_namespace }}"
  ignore_errors: yes
  when: delete_deployment|bool
  tags: 
    - amq
    - acm-workload