- name: Copying over quarkus-cafe-web application
  template:
    src: template/s2i/quarkus-cafe-web.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-web.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_owner }}"
    mode: 0666
  when: not skip_quarkus_cafe_web and deployment_method == "s2i"

- name: Copying over quarkus-cafe-web application
  template:
    src: templates/docker/quarkus-cafe-web.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-web.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_owner }}"
    mode: 0666
  when: not skip_quarkus_cafe_web  and  deployment_method == "docker"

- name: Create quarkus-cafe-web instance
  command: "oc create -f {{ config_location }}/quarkus-cafe-web.yaml"
  when: not delete_deployment|bool

- name: Waiting for quarkus-cafe-web build to complete
  shell: |
    set -o pipefail && oc get pods  | grep Completed | grep quarkus-cafe-web | wc -l
  register: install_status
  when: not delete_deployment|bool and deployment_method == "s2i"
  until: "'2' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for quarkus-cafe-web deployment
  shell: |
    set -o pipefail && oc get pods  | grep Running | grep quarkus-cafe-web | wc -l
  register: install_status
  when: not delete_deployment|bool
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15

- name: Delete quarkus-cafe-web instance
  command: "oc delete -f {{ config_location }}/quarkus-cafe-web.yaml"
  ignore_errors: yes
  when: delete_deployment|bool
  args:
    executable: /bin/bash

